# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.11.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.11.3/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/mike/projects/ed448goldilocks-code

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/mike/projects/ed448goldilocks-code

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.11.3/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.11.3/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.11.3/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.11.3/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.11.3/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.11.3/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/Cellar/cmake/3.11.3/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.11.3/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.11.3/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/local/Cellar/cmake/3.11.3/bin/cpack --config ./CPackSourceConfig.cmake /Users/mike/projects/ed448goldilocks-code/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/local/Cellar/cmake/3.11.3/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mike/projects/ed448goldilocks-code/CMakeFiles /Users/mike/projects/ed448goldilocks-code/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mike/projects/ed448goldilocks-code/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named doc

# Build rule for target.
doc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc
.PHONY : doc

# fast build rule for target.
doc/fast:
	$(MAKE) -f CMakeFiles/doc.dir/build.make CMakeFiles/doc.dir/build
.PHONY : doc/fast

#=============================================================================
# Target rules for targets named decaf

# Build rule for target.
decaf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 decaf
.PHONY : decaf

# fast build rule for target.
decaf/fast:
	$(MAKE) -f src/CMakeFiles/decaf.dir/build.make src/CMakeFiles/decaf.dir/build
.PHONY : decaf/fast

#=============================================================================
# Target rules for targets named decaf-static

# Build rule for target.
decaf-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 decaf-static
.PHONY : decaf-static

# fast build rule for target.
decaf-static/fast:
	$(MAKE) -f src/CMakeFiles/decaf-static.dir/build.make src/CMakeFiles/decaf-static.dir/build
.PHONY : decaf-static/fast

#=============================================================================
# Target rules for targets named CURVE25519

# Build rule for target.
CURVE25519: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CURVE25519
.PHONY : CURVE25519

# fast build rule for target.
CURVE25519/fast:
	$(MAKE) -f src/curve25519/CMakeFiles/CURVE25519.dir/build.make src/curve25519/CMakeFiles/CURVE25519.dir/build
.PHONY : CURVE25519/fast

#=============================================================================
# Target rules for targets named CURVE448

# Build rule for target.
CURVE448: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CURVE448
.PHONY : CURVE448

# fast build rule for target.
CURVE448/fast:
	$(MAKE) -f src/ed448goldilocks/CMakeFiles/CURVE448.dir/build.make src/ed448goldilocks/CMakeFiles/CURVE448.dir/build
.PHONY : CURVE448/fast

#=============================================================================
# Target rules for targets named p25519

# Build rule for target.
p25519: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p25519
.PHONY : p25519

# fast build rule for target.
p25519/fast:
	$(MAKE) -f src/p25519/CMakeFiles/p25519.dir/build.make src/p25519/CMakeFiles/p25519.dir/build
.PHONY : p25519/fast

#=============================================================================
# Target rules for targets named p448

# Build rule for target.
p448: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p448
.PHONY : p448

# fast build rule for target.
p448/fast:
	$(MAKE) -f src/p448/CMakeFiles/p448.dir/build.make src/p448/CMakeFiles/p448.dir/build
.PHONY : p448/fast

#=============================================================================
# Target rules for targets named generatedCode

# Build rule for target.
generatedCode: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 generatedCode
.PHONY : generatedCode

# fast build rule for target.
generatedCode/fast:
	$(MAKE) -f src/generator/CMakeFiles/generatedCode.dir/build.make src/generator/CMakeFiles/generatedCode.dir/build
.PHONY : generatedCode/fast

#=============================================================================
# Target rules for targets named decaf_tables

# Build rule for target.
decaf_tables: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 decaf_tables
.PHONY : decaf_tables

# fast build rule for target.
decaf_tables/fast:
	$(MAKE) -f src/generator/CMakeFiles/decaf_tables.dir/build.make src/generator/CMakeFiles/decaf_tables.dir/build
.PHONY : decaf_tables/fast

#=============================================================================
# Target rules for targets named generatorCommonCode

# Build rule for target.
generatorCommonCode: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 generatorCommonCode
.PHONY : generatorCommonCode

# fast build rule for target.
generatorCommonCode/fast:
	$(MAKE) -f src/generator/CMakeFiles/generatorCommonCode.dir/build.make src/generator/CMakeFiles/generatorCommonCode.dir/build
.PHONY : generatorCommonCode/fast

#=============================================================================
# Target rules for targets named decaf_gen_tables_curve25519

# Build rule for target.
decaf_gen_tables_curve25519: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 decaf_gen_tables_curve25519
.PHONY : decaf_gen_tables_curve25519

# fast build rule for target.
decaf_gen_tables_curve25519/fast:
	$(MAKE) -f src/generator/curve25519/CMakeFiles/decaf_gen_tables_curve25519.dir/build.make src/generator/curve25519/CMakeFiles/decaf_gen_tables_curve25519.dir/build
.PHONY : decaf_gen_tables_curve25519/fast

#=============================================================================
# Target rules for targets named generatorP25519

# Build rule for target.
generatorP25519: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 generatorP25519
.PHONY : generatorP25519

# fast build rule for target.
generatorP25519/fast:
	$(MAKE) -f src/generator/curve25519/CMakeFiles/generatorP25519.dir/build.make src/generator/curve25519/CMakeFiles/generatorP25519.dir/build
.PHONY : generatorP25519/fast

#=============================================================================
# Target rules for targets named decaf_tables_curve25519

# Build rule for target.
decaf_tables_curve25519: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 decaf_tables_curve25519
.PHONY : decaf_tables_curve25519

# fast build rule for target.
decaf_tables_curve25519/fast:
	$(MAKE) -f src/generator/curve25519/CMakeFiles/decaf_tables_curve25519.dir/build.make src/generator/curve25519/CMakeFiles/decaf_tables_curve25519.dir/build
.PHONY : decaf_tables_curve25519/fast

#=============================================================================
# Target rules for targets named generatorCurve25519

# Build rule for target.
generatorCurve25519: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 generatorCurve25519
.PHONY : generatorCurve25519

# fast build rule for target.
generatorCurve25519/fast:
	$(MAKE) -f src/generator/curve25519/CMakeFiles/generatorCurve25519.dir/build.make src/generator/curve25519/CMakeFiles/generatorCurve25519.dir/build
.PHONY : generatorCurve25519/fast

#=============================================================================
# Target rules for targets named decaf_tables_ed448goldilocks

# Build rule for target.
decaf_tables_ed448goldilocks: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 decaf_tables_ed448goldilocks
.PHONY : decaf_tables_ed448goldilocks

# fast build rule for target.
decaf_tables_ed448goldilocks/fast:
	$(MAKE) -f src/generator/ed448goldilocks/CMakeFiles/decaf_tables_ed448goldilocks.dir/build.make src/generator/ed448goldilocks/CMakeFiles/decaf_tables_ed448goldilocks.dir/build
.PHONY : decaf_tables_ed448goldilocks/fast

#=============================================================================
# Target rules for targets named generatorEd448goldilocks

# Build rule for target.
generatorEd448goldilocks: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 generatorEd448goldilocks
.PHONY : generatorEd448goldilocks

# fast build rule for target.
generatorEd448goldilocks/fast:
	$(MAKE) -f src/generator/ed448goldilocks/CMakeFiles/generatorEd448goldilocks.dir/build.make src/generator/ed448goldilocks/CMakeFiles/generatorEd448goldilocks.dir/build
.PHONY : generatorEd448goldilocks/fast

#=============================================================================
# Target rules for targets named decaf_gen_tables_ed448goldilocks

# Build rule for target.
decaf_gen_tables_ed448goldilocks: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 decaf_gen_tables_ed448goldilocks
.PHONY : decaf_gen_tables_ed448goldilocks

# fast build rule for target.
decaf_gen_tables_ed448goldilocks/fast:
	$(MAKE) -f src/generator/ed448goldilocks/CMakeFiles/decaf_gen_tables_ed448goldilocks.dir/build.make src/generator/ed448goldilocks/CMakeFiles/decaf_gen_tables_ed448goldilocks.dir/build
.PHONY : decaf_gen_tables_ed448goldilocks/fast

#=============================================================================
# Target rules for targets named generatorP448

# Build rule for target.
generatorP448: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 generatorP448
.PHONY : generatorP448

# fast build rule for target.
generatorP448/fast:
	$(MAKE) -f src/generator/ed448goldilocks/CMakeFiles/generatorP448.dir/build.make src/generator/ed448goldilocks/CMakeFiles/generatorP448.dir/build
.PHONY : generatorP448/fast

#=============================================================================
# Target rules for targets named shakesum_tester

# Build rule for target.
shakesum_tester: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 shakesum_tester
.PHONY : shakesum_tester

# fast build rule for target.
shakesum_tester/fast:
	$(MAKE) -f test/CMakeFiles/shakesum_tester.dir/build.make test/CMakeFiles/shakesum_tester.dir/build
.PHONY : shakesum_tester/fast

#=============================================================================
# Target rules for targets named bench

# Build rule for target.
bench: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bench
.PHONY : bench

# fast build rule for target.
bench/fast:
	$(MAKE) -f test/CMakeFiles/bench.dir/build.make test/CMakeFiles/bench.dir/build
.PHONY : bench/fast

#=============================================================================
# Target rules for targets named ristretto_tester

# Build rule for target.
ristretto_tester: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ristretto_tester
.PHONY : ristretto_tester

# fast build rule for target.
ristretto_tester/fast:
	$(MAKE) -f test/CMakeFiles/ristretto_tester.dir/build.make test/CMakeFiles/ristretto_tester.dir/build
.PHONY : ristretto_tester/fast

#=============================================================================
# Target rules for targets named decaf_tester

# Build rule for target.
decaf_tester: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 decaf_tester
.PHONY : decaf_tester

# fast build rule for target.
decaf_tester/fast:
	$(MAKE) -f test/CMakeFiles/decaf_tester.dir/build.make test/CMakeFiles/decaf_tester.dir/build
.PHONY : decaf_tester/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... doc"
	@echo "... test"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... package_source"
	@echo "... package"
	@echo "... decaf"
	@echo "... decaf-static"
	@echo "... CURVE25519"
	@echo "... CURVE448"
	@echo "... p25519"
	@echo "... p448"
	@echo "... generatedCode"
	@echo "... decaf_tables"
	@echo "... generatorCommonCode"
	@echo "... decaf_gen_tables_curve25519"
	@echo "... generatorP25519"
	@echo "... decaf_tables_curve25519"
	@echo "... generatorCurve25519"
	@echo "... decaf_tables_ed448goldilocks"
	@echo "... generatorEd448goldilocks"
	@echo "... decaf_gen_tables_ed448goldilocks"
	@echo "... generatorP448"
	@echo "... shakesum_tester"
	@echo "... bench"
	@echo "... ristretto_tester"
	@echo "... decaf_tester"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

